#' @title Add Variables
#'
#' @description Add home_score, away_score, home_points,
#' away_points, home_abbr and away_abbr variables to
#' a matches dataset.
#'
#' @param matches_dataset A tibble with matches data
#' generated by brasileirao package
#'
#' @return A tibble with added variables
#'
#' @export
#'
#' @examples
#' add_variables(matches)
#'
add_variables <- function(matches_dataset) {

  teams_abbr <- brasileirao::teams |>
    dplyr::select(team, abbr)

  matches2 <- matches_dataset |>
    dplyr::mutate(home_score = as.numeric(stringr::str_extract(score, "[:digit:]{1,2}(?=x)")),
                  away_score = as.numeric(stringr::str_extract(score, "(?<=x)[:digit:]{1,2}")),
                  home_points = dplyr::case_when(home_score >  away_score ~ 3,
                                                 home_score == away_score ~ 1,
                                                 home_score <  away_score ~ 0),
                  away_points = dplyr::case_when(away_score >  home_score ~ 3,
                                                 away_score == home_score ~ 1,
                                                 away_score <  home_score ~ 0)) |>
    dplyr::left_join(teams_abbr, by = c("home" = "team") ) |>
    dplyr::left_join(teams_abbr, by = c("away" = "team")) |>
    dplyr::rename(
      "home_abbr" = "abbr.x",
      "away_abbr" = "abbr.y"
    )

  return(matches2)

}
